server:
  port: 80
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: didi-zuul
  redis:
    host: 192.168.172.128
    password: 123456
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    crowd-portal:
      service-id: didi-auth-crowd
      path: /**
    crowd-project:
      service-id: didi-crowd-pro
      path: /project/**
    order-project:
      service-id: didi-crowd-order
      path: /order/**
    pay-project:
      service-id: didi-crowd-pay
      path: /pay/**
    realname-project:
      service-id: didi-crowd-realname
      path: /realname/**
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

