server:
  port: 8000
spring:
  application:
    name: didi-crowd-pay
  redis:
    password: 123456
    host: 192.168.172.128
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgd+aftMFQ9RmZ818Ka+yzKAbFTv9SQOZm9EMg+LsTko6B3DqQViMGNa/ztthVU2WEIWdHF3jNsxkBXG7yN3TVpW54AkOI359MS/zPLjZ+t+KHxZlR685eCx2H4YAH6wOeWQtVAmyIhbnRyVnh8NScDpIp+eI3+zFS63sHMiyQHo4rlKzyVn6jfHIngzO8FUlEKCSvK1nC2Kf0lNDgT3X3AHENK+eIOFegcATCSG7rGjR3rD3LHBzXlsp9PuncGxUZPb8pJNCShu/Q57nvCWDOjk6x9ezqUm/x17B/6krd5iKLrt4QQti1y4NRf1WmLh30ltO23xk4oaB4EW39zJT7QIDAQAB
    app-id: 2016102600764170
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQClW8hGJ5W+IeZThblsnQ6f63UTk1TYIpLHr9PSX+0xDISSMOOcTcWVJ6dvZtoZ0uDj39bJchNJMEv5CGZ6YyYqPbp4sVulv7ZJNGU3igsAZ0ooBlOngvg8n4uFHuhvkUeAQA9F6nCWW9NEBvD0AxCca087Z1N34WWTING3QneQ6A7YslL9eov61ZPGytWrntrVoq/8n8FVus+tBW70BpJONwEQFcdssHMJ/x7EtR15KTYKX4MCn3CGXCBpZLxFQqu0jPdqbC1dhPs7mL+uxdvHrB8LDisqBbUyvzUix3pDlDaK36id1gd/XmQO7Ov37bCpsXuy4J2DxJpdr6n3NWcLAgMBAAECggEBAIQDR1uCxNB7PeeWTdeBd6iCkQBk0gqPZ4FWRRSiErni1X/k2gHyMPiIJOsSQLL3ISWrkU1X7j+y+CRD6ZRxzYlRqKosZg9og33j/56cbXYQACr+ChEkxUuY0AkiCMzxPhUMj2Tw6puPiZW4uOsF+1/1Z9b0AbYmUzJntCXLQauD2R7m1WXTDp4tbT074dP8mrgQUj+JJFkhput7CEJ0zWONLretzlk2YFpbCVTK65ZyMvUSUWTYNgROP1KuKb5Bqnt3x23Ks2Ragg4uPWDilOpweq0758qRMBop4/ch1+lKPUnKOc1aI+OLZXpHlPVJuolTY3pXL8QM0nV/5Mj7Z2kCgYEA+1k2G2Fu9GrRPiZnWbH3ry5jPVonl/VOlmauBJIVIMCTetikk/kvxku1ZB9RVnUTf0BehkbU4TH4WizWf1z6BaGtMJ92YhhKQqRF1WpxJbs4RL8TcYJ9UpqWnM9qS5blsOijW17nUtw96biAzaOtb/va9kSJPCtNpODSYY4lnycCgYEAqGsvVsTfw7Cze4xF/qAWPDtjn8lqLGitUXlp26o158htwVP60VqYKGW13jVSeW7KJYIx2F5ya5vxG1fxi+aWvsHzGphbfxLNzb/ZoLn3LhDZbF15NLK1SyVgb87CH0BllgUS7zs5U10Rvs4dzA5bmsu0Ve6tmhjKdU19Z9aCZ30CgYA5q41zmNZ5dCzQYsVh2iinZDBW+mGNRzah4atZ1x7L5gOwsxaH8SvaBrL25wyllrVDhERr8MKVbP67yf/pNy8SrbbsKhpihYo8Yi63ufV+H8fYVjMi3zrcAiY+koSkFVpcTfR1WYAgDfKStseu5zg7MoFZ8f2+9XyaMQ90XMYbDwKBgQClpK3tkDpoVH1ikScydK8J1Ht6Z3XWcamtTVXRJ4pXCijwkTFKAOlQKiECiL0yE8Ybt/5gSRwOPFSZyRgXudYfjdAVIy4yQANMTlm0G9NBam79hr20F+P5IazEqr0AUazYLOtfgYczN4FBgaWK0cBE8f7O2a3CtolBb9Jcc3zUXQKBgQCvA3llb1F3p6P2tDmz516dg4+YhxGO8F4DgcPTmeEEEyKrRsFf01z8eqhwKPiqmfJV/nvQtV7Egjo8IoJZ/8zM0tgZdvF58Mu7vB2Kj0n4alegYjHkMPz9HMvx5ciuKXU4Z67xFnyeOexQPfz4v0vBIn/SFBcG8zYOKRk8tW/jZg==
    notify-url: http://6buqxk.natappfree.cc/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000