server:
  port: 8000
spring:
  application:
    name: didi-crowd-pay
  redis:
    password: 123456
    host: 192.168.172.128
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    alipay-public-key: MIIBIjANBgk685eCx2H4YAH6wOeWQtVAmyIhbnRyVnh8NScD
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvTcWVJ6dvZtoZ0uD
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
